config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
      registrations: 'users/registrations',
      sessions: 'users/sessions'
  }
  root to: 'home#top'
  get 'home/about'
  resources :books
  resources :users, only: [:index, :show, :edit, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user

  validates :title,
            presence: true
  validates :body,
            presence: true,
            length: { minimum: 0, maximum: 200 }

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update]

  def index
    @books = Book.all.order(created_at: :desc)
    @user = current_user
    @book_new = Book.new
  end

  def show
    @book = Book.find(params[:id])
    @user = current_user
    @book_new = Book.new
  end

  def create
    @book_new = Book.new(book_params)
    @book_new.user_id = current_user.id
    if @book_new.save
      redirect_to book_path(@book_new), notice: 'You have created book successfully'
    else
      @books = Book.all.order(created_at: :desc)
      @user = current_user
      render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def correct_user
    book = Book.find(params[:id])
    if current_user.id != book.user.id
      redirect_to books_path
    end
  end

  def book_params
    params.require(:book).permit(:title, :body, :user_id)
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<p id="notice"></p>
<% if @book.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <h2><%= @book.errors.count %>errors prohibited this obj from being saved:</h2>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1>Editing Book</h1>
    <%= form_for(@book) do |f| %>
      <div class="field">
        <label for="book_title">Title</label><br>
        <%= f.text_field :title, class:"col-xs-12 book_title" %>
      </div>
      <div class="field">
        <label for="book_opinion">Opinion</label><br>
        <%= f.text_area :body, class:"col-xs-12 book_body" %>
      </div>
      <div class="actions">
        <%= f.submit 'Update Book', class:"btn btn-primary col-xs-12" %>
      </div>
    <% end %>
    <%= link_to "Show", book_path(@book) %> |
    <%= link_to "Back", books_path %>
  </div>
  <div class="col-md-3"></div>
</div>

app/views/books/index.html.erb
<p id="notice"></p>
<% if @book_new.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <h2><%= @book_new.errors.count %>errors prohibited this obj from being saved:</h2>
    <ul>
      <% @book_new.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<div class='row'>
  <%= render 'users/list', book_new: @book_new, user: @user %>
  <div class="col-md-8 offset-md-1">
    <h2>Books</h2>
    <table class="table table-hover table-inverse">
      <thead>
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(book.user) do %>
                <%= attachment_image_tag book.user, :profile_image, :fill, 60, 60, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg" %>
              <% end %>
            </td>
            <td><%= link_to book.title, book_path(book) %></td>
            <td><%= book.body %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
</div>

app/views/books/show.html.erb
<p id="notice"></p>
<div class='row'>

  <%= render 'users/list', book_new: @book_new, user: @book.user %>

  <div class="col-md-8 offset-md-1">
    <h2>Book detail</h2>
    <table class="table">
      <tbody>
        <tr>
          <td>
            <%= link_to user_path(@book.user) do %>
              <%= attachment_image_tag @book.user, :profile_image, :fill, 60, 60, format: 'jpeg', class: "attachment user profile_image fallback", fallback: "no_image.jpg" %>
              <%= link_to @book.user.name, user_path(@book.user), style:"margin-left:10px;" %>
            <% end %>
          </td>
          <td><%= @book.title %></td>
          <td><%= @book.body %></td>
          <% if @book.user == current_user %>
            <td><%= link_to "Edit", edit_book_path(@book), class:'btn-sm btn-success' %></td>
            <td><%= link_to "Destroy", book_path(@book), method: :delete, class:'btn-sm btn-danger', "data-confirm" => "Are you sure?" %></td>
          <% end %>
        </tr>
      </tbody>
    </table>
  </div>
</div>